# Happy Coding!

service: serverless-blog

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1

functions:
  user:
    handler: functions/user.index
    events: 
      - http:
          path: /user
          method: ANY
          cors: true
      - http:
          path: /user/{proxy+}
          method: ANY
          cors: true

  post:
    handler: functions/post.index
    events: 
      - http:
          path: /post
          method: ANY
          cors: true
      - http:
          path: /post/{proxy+}
          method: ANY
          cors: true

  comment:
    handler: functions/comment.index
    events: 
      - http:
          path: /comment
          method: ANY
          cors: true
      - http:
          path: /comment/{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin